name: cs50
channels:
  - javascript
dependencies:
  - python=3.6
  - flask
  - sqlalchemy
  - psycopg2
  - jupyter
  - pandas
  - flask-sqlalchemy
  - requests
  - pip:
    - Flask-Testing
    - Flask-Session