# Generated by Django 2.2.5 on 2019-09-25 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='large',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='small',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
    ]
