# Generated by Django 2.2.5 on 2019-09-25 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190925_0606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='large',
        ),
        migrations.RemoveField(
            model_name='category',
            name='small',
        ),
    ]
