# Generated by Django 2.2.5 on 2019-09-25 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_salads'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Salads',
            new_name='Salad',
        ),
    ]
